import { Datasource } from "./datasource-columns";

export const data: Datasource[] = [
  {
    name: "website - data",
    type: "PDF",
    status: "Uploaded",
    createdAt: new Date("2024-01-06"),
    createdBy: "Olivia Ryhe",
  },
  {
    name: "website - data",
    type: "PDF",
    status: "Uploaded",
    createdAt: new Date("2024-01-28"),
    createdBy: "Natalie Crag",
  },
  {
    name: "Products",
    type: "CSV",
    status: "Uploaded",
    createdAt: new Date("2024-02-04"),
    createdBy: "Phoenix Baker",
  },
  {
    name: "user - data",
    type: "CSV",
    status: "Connected",
    createdAt: new Date("2024-02-08"),
    createdBy: "Natalie Crag",
  },
  {
    name: "website - data",
    type: "DOCX",
    status: "Uploaded",
    createdAt: new Date("2024-03-07"),
    createdBy: "Olivia Ryhe",
  },
  {
    name: "website - data",
    type: "CSV",
    status: "Uploaded",
    createdAt: new Date("2024-03-07"),
    createdBy: "Phoenix Baker",
  },
  {
    name: "Server Files",
    type: "DOCX",
    status: "Uploaded",
    createdAt: new Date("2024-03-21"),
    createdBy: "Natalie Crag",
  },
  {
    name: "website - data",
    type: "CSV",
    status: "Uploaded",
    createdAt: new Date("2024-03-28"),
    createdBy: "Olivia Ryhe",
  },
  {
    name: "user - data",
    type: "PDF",
    status: "Connected",
    createdAt: new Date("2024-06-09"),
    createdBy: "Natalie Crag",
  },
  {
    name: "user - data",
    type: "DOCX",
    status: "Connected",
    createdAt: new Date("2024-06-29"),
    createdBy: "Olivia Ryhe",
  },
  {
    name: "user - data",
    type: "DOCX",
    status: "Connected",
    createdAt: new Date("2024-07-02"),
    createdBy: "Phoenix Baker",
  },
  {
    name: "user - data",
    type: "DOCX",
    status: "Uploaded",
    createdAt: new Date("2024-08-01"),
    createdBy: "Natalie Crag",
  },
  {
    name: "website - data",
    type: "PDF",
    status: "Uploaded",
    createdAt: new Date("2024-09-21"),
    createdBy: "Olivia Ryhe",
  },
  {
    name: "Server Files",
    type: "CSV",
    status: "Connected",
    createdAt: new Date("2024-09-21"),
    createdBy: "Natalie Crag",
  },
  {
    name: "website - data",
    type: "PDF",
    status: "Uploaded",
    createdAt: new Date("2024-09-21"),
    createdBy: "Alivia Ryhe",
  },
  {
    name: "Server Files",
    type: "CSV",
    status: "Connected",
    createdAt: new Date("2025-01-21"),
    createdBy: "Natalie Crag",
  },
];
